version: 1.2
workflows:
  - subclass: WDL 
    primaryDescriptorPath: /workflows/FilterRareVariants.wdl
    name: FilterRareVariants
  - subclass: WDL 
    primaryDescriptorPath: /workflows/CallZscoresAcrossPCs.wdl
    name: CallZscoresAcrossPCs
